server:
  port: 7003

#Eureka 配置
eureka:
  instance:
    hostname: eureka7003.com  #Eureka服务端的实力名称
  client:
    register-with-eureka: false   #表示是否想注册中心注册自己
    fetch-registry: false   #fetch-registry 如果为false，则表示自己为注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
